language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: Vkyt3AO5lGIElkoWLvZl2i3OMx03DpCGaI7CeM7EDR19vor/oHfgJIzJi20HYtPXyzbMApqNRqd7BozAk1ea2Caaj/6PY6W5H5Qn0ixUiXDi2AAEzAorTdH3jaVeRkEqMyHY5K97ugtWBx7G2AVbw4/tz+eG40xOONkYGex1BCdd10bURd6/pZSypbCy/cg5DbU60VfFhcRcRFyCQUVwEJxT4sgztTnmjpME8pQUqqXWLWhr6RMcfPnruItu0dfODOFncIUWNC3dXRLo053AX5n/nRKnsA4qInG0w2/sUIfX33VZs1WrUmwQ8vpLi5Qt95lY7gibtwK28K7fGh0Rhn8k+NUHVzuj7rx1oORd6L1zzZFoUtLnqbq1mYxKGe2c2jHFppkAFlAskJeGuuPQCGOP7LSeS0W93n88HHTlxO8TNFofK2DKhqLSVg49k06/5IMaViJ881Lh+rLxMDKObiPaV9aG1sNnEOsULVY7ZhAUeVTpLQXkvOGEq+aPU3kWQW7X+aqfvaSkA6IryhXGfc1eqQR542QGu5VHcAm9ARRXCNqyCt6PDQPaWD3IrWk9b/Ob4Z5Q0IbqyU+wM52KSLfPaoLLUM0gpsREKSQ81UwPROTeANiE+vlHQQxOyj9E4BLoZ96Js2jDY72I238F1Vd7TaV2AymVOYug7AT2sEg=
  app: paloma-pies
  skip_cleanup: true
